redmine_app_port: 3000

datadog_site: "datadoghq.com"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: Application health check status
        url: http://hexlet.devops-and1.club:5000
        timeout: 5
        method: GET
