- name: Deploy
  hosts: all
  remote_user: root
  tasks:
    - name: Install packages
      apt:
        name: python3-pip
        update_cache: yes

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Run container
      community.docker.docker_container:
        name: devops-example-app
        image: 0136/devops-example-app
        published_ports: 5000:5000
        restart_policy: always
        restart: yes
        container_default_behavior: no_defaults
        pull: yes
        env:
          SERVER_MESSAGE: "{{ ansible_default_ipv4.address }}"

- name: Datadog http check
  hosts: webservers
  gather_facts: no
  roles:
    - role: datadog.datadog