- name: Setup Infrastructure
  hosts: all
  connection: local
  roles:
    - name: infrastructure
      vars:
        terraform_dir: "{{ playbook_dir }}/../terraform"

- name: Deploy
  hosts: all
  remote_user: root
  tasks:
    - name: Install packages
      apt:
        name: python3-pip
        update_cache: yes

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Add the user 'deploy' with a primary group of 'docker'
      ansible.builtin.user:
        name: deploy
        group: docker

    - name: Set authorized key in alternate location
      ansible.posix.authorized_key:
        user: deploy
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: Log into DockerHub
      community.docker.docker_login:
        username: "0136"
        password: "{{ docker_token }}"

    - name: Run container
      community.docker.docker_container:
        name: devops-example-app
        image: 0136/private-devops-example-app
        published_ports: 5000:5000
        restart_policy: always
        restart: yes
        container_default_behavior: no_defaults
        pull: yes
        env:
          SERVER_MESSAGE: "{{ ansible_default_ipv4.address }}"

- name: Datadog http check
  hosts: webservers
  gather_facts: no
  roles:
    - role: datadog.datadog